# Generated by Django 4.2.4 on 2023-08-25 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('school', models.CharField(choices=[('홍익대', '홍익대'), ('서강대', '서강대'), ('연세대', '연세대'), ('이화여대', '이화여대')], max_length=20)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_detail_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_detail_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('밴드', '밴드'), ('댄스', '댄스'), ('전시', '전시'), ('연극', '연극'), ('스포츠', '스포츠'), ('기타', '기타')], max_length=20)),
                ('start_day', models.DateField(null=True)),
                ('finish_day', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('long', models.CharField(max_length=50)),
                ('pay', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('contact', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
